import Head from 'next/head';
import Slider from "./components/Slider";
import styled from 'styled-components';

const App1 = styled.main`
  text-align: center;
  display: flex;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ocean-Carousel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://use.typekit.net/izy8aoj.css"/>
      </Head>

      <App1>
        <Slider />
      </App1>
    </div>
  )
}
